#define OVERRIDE_MAC false
#define MY_MAC 0b011
//DELAY FOR READING LCD SCREEN
#define READ_DELAY 200                           
//LIMIT FOR BUFFER LENGTH
#define BUFFER_LIMIT 8


//HEADERS

//PLACE OF THE DEST_MAC
#define DEST_MAC 0
//PLACE OF THE SRC MAC
#define SRC_MAC 1
//PLACE OF THE TYPE HEADER
#define TYPE 2
//PLACE OF CHECKSUM
#define CHECKSUM 3
//PLACE OF DEST IP ADDRESS
#define DEST_IP 4
//PLACE OF SRC IP ADDRESS
#define SRC_IP 5
//PLACE OF TTL HEADER
#define TTL 6
//PLACE OF NEXT PROTOCOL HEADER
#define NEXT_PROTOCOL 7



// PhysicalLayer


//PhysicalLayer TIMEOUT IN MS -> 1000 = 2sec
#define PhysicalLayer_TIMEOUT 1000 
//HOW FAST SHOULD FRAMES BE TRANSMITTED. THE HIGHER, THE SLOWER IS TRANSMISSION, SHOULD BE [200, 15000] (Microseconds) 
#define MESSAGE_TIME  500
//MESSAGE SIZE IN BYTES MAX. 16
#define MESSAGE_SIZE 16

//PINS OF THE PORTS
#define NR_OF_PORTS 5
#define SEND_PORT_1 9
#define SEND_PORT_2 10
#define SEND_PORT_3 11
#define SEND_PORT_4 12
#define SEND_PORT_5 13
#define RECEIVE_PORT_1 A0
#define RECEIVE_PORT_2 A1
#define RECEIVE_PORT_3 A2
#define RECEIVE_PORT_4 A3
#define RECEIVE_PORT_5 A4

//TIME INTERVAL FOR CHECKING PORTS DURING SENDING/RECEIVING
#define FLANK_AWAIT_TIME 1 //in us



// HARDWARE

//PINS OF THE LCD
#define RS 7
#define EN 6
#define D4 5
#define D5 4
#define D6 3
#define D7 2

#define MAC_PIN A5
